version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - 8090:8090
    links:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 1521
  db:
    image: oracleinanutshell/oracle-xe-11g:latest
    ports:
      - 1521:1521
      - 5500:5500
volumes:
  logvolume01: {}
